/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";

export function Airplane(props) {
  const { nodes, materials } = useGLTF("./models/boat/model.gltf");

  return (
    <group {...props} dispose={null}>
      <mesh>
        <meshStandardMaterial />
      </mesh>
      <mesh
        geometry={nodes.Sketchfab_Scene.geometry}
        position={[1.09, 0.23, 0]}
      >
        <meshStandardMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/boat/model.gltf");
