/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { memo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";


export const Island = memo(({ sceneOpacity, ...props }) => {
  const { nodes, materials } = useGLTF("./models/medieval_castle_with_village/scene.gltf");

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  return (
    <group {...props} dispose={null}>
     <group>
        {Object.keys(nodes).map((Sketchfab_model) => (
          <mesh
            key={Sketchfab_model}
            geometry={nodes[Sketchfab_model].geometry}
          >
            <meshStandardMaterial
              ref={materialRef}
              onBeforeCompile={fadeOnBeforeCompile}
              envMapIntensity={2}
              transparent
            />
          </mesh>
        ))}
      </group>
    </group>
  );
});

useGLTF.preload([
  "./models/medieval_castle_with_village/scene.gltf", 
  "./models/medieval_castle_with_village/textures/gray.067_baseColor.png",
  "./models/medieval_castle_with_village/textures/black.037_0_baseColor.png",
  "./models/medieval_castle_with_village/textures/blue.016_baseColor.png",
  "./models/medieval_castle_with_village/textures/brick.006_baseColor.png",
  "./models/medieval_castle_with_village/textures/brick.006_normal.png",
  "./models/medieval_castle_with_village/textures/brown.086_baseColor.png",
  "./models/medieval_castle_with_village/textures/dirt.001_baseColor.png",
  "./models/medieval_castle_with_village/textures/dirt.001_normal.png",
  "./models/medieval_castle_with_village/textures/dirtroad.003_baseColor.png",
  "./models/medieval_castle_with_village/textures/dirtroad.003_normal.png",
  "./models/medieval_castle_with_village/textures/dkbrown.025_baseColor.png",
  "./models/medieval_castle_with_village/textures/dkbrown.025_0_baseColor.png",
  "./models/medieval_castle_with_village/textures/dkgreen.016_baseColor.png",
  "./models/medieval_castle_with_village/textures/grass.013_baseColor.png",
  "./models/medieval_castle_with_village/textures/gray.059_baseColor.png",
  "./models/medieval_castle_with_village/textures/green.002_baseColor.png",
  "./models/medieval_castle_with_village/textures/litblue.002_baseColor.png",
  "./models/medieval_castle_with_village/textures/litblue.002_metallicRoughness.png",
  "./models/medieval_castle_with_village/textures/ltgray.030_baseColor.png",
  "./models/medieval_castle_with_village/textures/pink_baseColor.png",
  "./models/medieval_castle_with_village/textures/red.006_baseColor.png",
  "./models/medieval_castle_with_village/textures/schingle.007_baseColor.png",
  "./models/medieval_castle_with_village/textures/schingle.007_normal.png",
  "./models/medieval_castle_with_village/textures/skincolr.001_baseColor.png",
  "./models/medieval_castle_with_village/textures/smlstone.043_baseColor.png",
  "./models/medieval_castle_with_village/textures/smlstone.043_normal.png",
  "./models/medieval_castle_with_village/textures/smlstone.043_0_baseColor.png",
  "./models/medieval_castle_with_village/textures/smlstone.043_0_normal.png",
  "./models/medieval_castle_with_village/textures/tile.009_baseColor.png",
  "./models/medieval_castle_with_village/textures/tile.009_normal.png",
  "./models/medieval_castle_with_village/textures/trubrown.024_baseColor.png",
  "./models/medieval_castle_with_village/textures/white.025_baseColor.png",
  "./models/medieval_castle_with_village/textures/window.008_baseColor.png",
  "./models/medieval_castle_with_village/textures/window.008_normal.png",
  "./models/medieval_castle_with_village/textures/wood.045_baseColor.png",
  "./models/medieval_castle_with_village/textures/wood.045_normal.png",
  "./models/medieval_castle_with_village/textures/yellow.007_baseColor.png",
  "./models/medieval_castle_with_village/textures/yellwhit.015_baseColor.png"
]);

