/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";


export function Lighthouse ({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/lighthouse/scene.gltf");

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sketchfab_Scene.geometry}>
        <meshStandardMaterial
          ref={materialRef}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
    </group>
  );
};

useGLTF.preload("./models/lighthouse/model.gltf");

